# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecb9a2c44a47696367ea1eecc6d81b405ca8586a250540200a5442c1fd25717de57a19755861b8c0c33d51a86fecc5ae57af2e7bba7d7b16fb9635c8782cf6c0

test:
  secret_key_base: 6d61681f068d9898a7cd4cdeccbf2b09430c3dd4f2d69fb19888a3cd52bb91d8f904a498717e0ceb981e50ab78f0d1f767eb222d707018d2d813f931cdb963fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
